//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:22:28 PM EDT 
//


package com.raritan.dctrack.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataColumn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="valueIdField" type="{http://dctrack.raritan.com/xsd}uiValueIdField"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataColumn", propOrder = {
    "valueIdField"
})
public class DataColumn {

    @XmlElement(required = true)
    protected UiValueIdField valueIdField;

    /**
     * Gets the value of the valueIdField property.
     * 
     * @return
     *     possible object is
     *     {@link UiValueIdField }
     *     
     */
    public UiValueIdField getValueIdField() {
        return valueIdField;
    }

    /**
     * Sets the value of the valueIdField property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiValueIdField }
     *     
     */
    public void setValueIdField(UiValueIdField value) {
        this.valueIdField = value;
    }

}
