//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:22:28 PM EDT 
//


package com.raritan.dctrack.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.raritan.dctrack.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.raritan.dctrack.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DcTrack }
     * 
     */
    public DcTrack createDcTrack() {
        return new DcTrack();
    }

    /**
     * Create an instance of {@link UiViews }
     * 
     */
    public UiViews createUiViews() {
        return new UiViews();
    }

    /**
     * Create an instance of {@link UiView }
     * 
     */
    public UiView createUiView() {
        return new UiView();
    }

    /**
     * Create an instance of {@link UiViewPanel }
     * 
     */
    public UiViewPanel createUiViewPanel() {
        return new UiViewPanel();
    }

    /**
     * Create an instance of {@link UiComponents }
     * 
     */
    public UiComponents createUiComponents() {
        return new UiComponents();
    }

    /**
     * Create an instance of {@link AltUiValueIdFieldMap }
     * 
     */
    public AltUiValueIdFieldMap createAltUiValueIdFieldMap() {
        return new AltUiValueIdFieldMap();
    }

    /**
     * Create an instance of {@link UiComponent }
     * 
     */
    public UiComponent createUiComponent() {
        return new UiComponent();
    }

    /**
     * Create an instance of {@link UiValueIdField }
     * 
     */
    public UiValueIdField createUiValueIdField() {
        return new UiValueIdField();
    }

    /**
     * Create an instance of {@link UiLookupFields }
     * 
     */
    public UiLookupFields createUiLookupFields() {
        return new UiLookupFields();
    }

    /**
     * Create an instance of {@link DataRow }
     * 
     */
    public DataRow createDataRow() {
        return new DataRow();
    }

    /**
     * Create an instance of {@link DataColumn }
     * 
     */
    public DataColumn createDataColumn() {
        return new DataColumn();
    }

    /**
     * Create an instance of {@link UiDefaultType }
     * 
     */
    public UiDefaultType createUiDefaultType() {
        return new UiDefaultType();
    }

}
