//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:22:28 PM EDT 
//


package com.raritan.dctrack.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uiComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uiComponent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="uiLookupField" type="{http://dctrack.raritan.com/xsd}uiLookupFields" minOccurs="0"/&gt;
 *             &lt;element name="uiValueIdField" type="{http://dctrack.raritan.com/xsd}uiValueIdField" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="altUiValueIdFieldMap" type="{http://dctrack.raritan.com/xsd}altUiValueIdFieldMap" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="uiId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uiType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="remoteName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uiLabel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="lockStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="hide" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="classMountingFormFactorValue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uiComponent", propOrder = {
    "uiLookupField",
    "uiValueIdField",
    "altUiValueIdFieldMap"
})
public class UiComponent {

    protected UiLookupFields uiLookupField;
    protected UiValueIdField uiValueIdField;
    protected List<AltUiValueIdFieldMap> altUiValueIdFieldMap;
    @XmlAttribute(name = "uiId")
    protected String uiId;
    @XmlAttribute(name = "uiType")
    protected String uiType;
    @XmlAttribute(name = "remoteName")
    protected String remoteName;
    @XmlAttribute(name = "uiLabel")
    protected String uiLabel;
    @XmlAttribute(name = "editable")
    protected Boolean editable;
    @XmlAttribute(name = "lockStatus")
    protected Boolean lockStatus;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "hide")
    protected Boolean hide;
    @XmlAttribute(name = "classMountingFormFactorValue")
    protected String classMountingFormFactorValue;

    /**
     * Gets the value of the uiLookupField property.
     * 
     * @return
     *     possible object is
     *     {@link UiLookupFields }
     *     
     */
    public UiLookupFields getUiLookupField() {
        return uiLookupField;
    }

    /**
     * Sets the value of the uiLookupField property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiLookupFields }
     *     
     */
    public void setUiLookupField(UiLookupFields value) {
        this.uiLookupField = value;
    }

    /**
     * Gets the value of the uiValueIdField property.
     * 
     * @return
     *     possible object is
     *     {@link UiValueIdField }
     *     
     */
    public UiValueIdField getUiValueIdField() {
        return uiValueIdField;
    }

    /**
     * Sets the value of the uiValueIdField property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiValueIdField }
     *     
     */
    public void setUiValueIdField(UiValueIdField value) {
        this.uiValueIdField = value;
    }

    /**
     * Gets the value of the altUiValueIdFieldMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altUiValueIdFieldMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltUiValueIdFieldMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltUiValueIdFieldMap }
     * 
     * 
     */
    public List<AltUiValueIdFieldMap> getAltUiValueIdFieldMap() {
        if (altUiValueIdFieldMap == null) {
            altUiValueIdFieldMap = new ArrayList<AltUiValueIdFieldMap>();
        }
        return this.altUiValueIdFieldMap;
    }

    /**
     * Gets the value of the uiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiId() {
        return uiId;
    }

    /**
     * Sets the value of the uiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiId(String value) {
        this.uiId = value;
    }

    /**
     * Gets the value of the uiType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiType() {
        return uiType;
    }

    /**
     * Sets the value of the uiType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiType(String value) {
        this.uiType = value;
    }

    /**
     * Gets the value of the remoteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteName() {
        return remoteName;
    }

    /**
     * Sets the value of the remoteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteName(String value) {
        this.remoteName = value;
    }

    /**
     * Gets the value of the uiLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiLabel() {
        return uiLabel;
    }

    /**
     * Sets the value of the uiLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiLabel(String value) {
        this.uiLabel = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

    /**
     * Gets the value of the lockStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLockStatus() {
        return lockStatus;
    }

    /**
     * Sets the value of the lockStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLockStatus(Boolean value) {
        this.lockStatus = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the hide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHide() {
        return hide;
    }

    /**
     * Sets the value of the hide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHide(Boolean value) {
        this.hide = value;
    }

    /**
     * Gets the value of the classMountingFormFactorValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassMountingFormFactorValue() {
        return classMountingFormFactorValue;
    }

    /**
     * Sets the value of the classMountingFormFactorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassMountingFormFactorValue(String value) {
        this.classMountingFormFactorValue = value;
    }

}
