//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:22:28 PM EDT 
//


package com.raritan.dctrack.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uiViewPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uiViewPanel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uiViewComponents" type="{http://dctrack.raritan.com/xsd}uiComponents"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="uiLabel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uiId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uiViewPanel", propOrder = {
    "uiViewComponents"
})
public class UiViewPanel {

    @XmlElement(required = true)
    protected UiComponents uiViewComponents;
    @XmlAttribute(name = "editable")
    protected Boolean editable;
    @XmlAttribute(name = "uiLabel")
    protected String uiLabel;
    @XmlAttribute(name = "uiId")
    protected String uiId;

    /**
     * Gets the value of the uiViewComponents property.
     * 
     * @return
     *     possible object is
     *     {@link UiComponents }
     *     
     */
    public UiComponents getUiViewComponents() {
        return uiViewComponents;
    }

    /**
     * Sets the value of the uiViewComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiComponents }
     *     
     */
    public void setUiViewComponents(UiComponents value) {
        this.uiViewComponents = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

    /**
     * Gets the value of the uiLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiLabel() {
        return uiLabel;
    }

    /**
     * Sets the value of the uiLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiLabel(String value) {
        this.uiLabel = value;
    }

    /**
     * Gets the value of the uiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiId() {
        return uiId;
    }

    /**
     * Sets the value of the uiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiId(String value) {
        this.uiId = value;
    }

}
