//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:22:28 PM EDT 
//


package com.raritan.dctrack.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uiView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uiView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uiViewPanel" type="{http://dctrack.raritan.com/xsd}uiViewPanel" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="uiId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="remoteRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uiView", propOrder = {
    "uiViewPanel"
})
public class UiView {

    @XmlElement(required = true)
    protected List<UiViewPanel> uiViewPanel;
    @XmlAttribute(name = "uiId")
    protected String uiId;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "remoteRef")
    protected String remoteRef;
    @XmlAttribute(name = "editable")
    protected Boolean editable;

    /**
     * Gets the value of the uiViewPanel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uiViewPanel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUiViewPanel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UiViewPanel }
     * 
     * 
     */
    public List<UiViewPanel> getUiViewPanel() {
        if (uiViewPanel == null) {
            uiViewPanel = new ArrayList<UiViewPanel>();
        }
        return this.uiViewPanel;
    }

    /**
     * Gets the value of the uiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiId() {
        return uiId;
    }

    /**
     * Sets the value of the uiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiId(String value) {
        this.uiId = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the remoteRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteRef() {
        return remoteRef;
    }

    /**
     * Sets the value of the remoteRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteRef(String value) {
        this.remoteRef = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

}
