package com.raritan.tdz.changemgmt.home;

/**
 * An enumeration of supported "human" workflow tasks for change management.
 * These Human tasks require user intervention from the dcTrack GUI. 
 * @author Andrew Cohen
 * @version 3.0
 */
public enum ChangeMgmtWorkflowTask {

	CREATE_REQUEST,
	SUBMIT_REQUEST,
	DELETE_REQUEST,
	PROVISION_BASIC_INFORMATION,
	PROVISION_HARDWARE_INFORMATION,
	PROVISION_PLACEMENT_INFORMATION,
	PROVISION_ASSET_INFORMATION,
	PROVISION_OTHER_INFORMATION,
	PROVISION_APPLICATIONS,
	PROVISION_DATA_PORTS,
	PROVISION_POWER_PORTS,
	PROVISION_CONNECTIONS,
	TO_DO,
	ADD_ITEM_WORK_ORDER,
	REMOVE_ITEM_WORK_ORDER,
	MOVE_ITEM_WORK_ORDER,
	ADD_DATA_PANEL_WORKORDER,
	REMOVE_DATA_PANEL_WORKORDER,
	RENAME_ITEM_WORK_ORDER,
	ADD_CONNECTIONS_WORK_ORDER,
	REMOVE_CONNECTIONS_WORK_ORDER;
}
