package com.raritan.tdz.floormaps.domain;
// Generated 2013/8/5 03:41:28 by Hibernate Tools 3.4.0.CR1


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import com.raritan.tdz.domain.Item;
import com.raritan.tdz.domain.LkuData;
import com.raritan.tdz.domain.DataCenterLocationDetails;
import com.raritan.tdz.domain.cmn.Users;

/**
 * ReportThresholds generated by hbm2java
 */
@Entity
@Table(name="`dct_floormaps_report_thresholds`")
public class ReportThresholds  implements java.io.Serializable {
	
	@Id
	 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dct_floormaps_report_thresholds_seq")
	 @SequenceGenerator(name = "dct_floormaps_report_thresholds_seq", sequenceName = "dct_floormaps_report_threshol_floormaps_report_threshold_id_seq", allocationSize=1)
	 @Column(name="floormaps_report_threshold_id", unique=true, nullable=false)	
	 private Long id;
	 
	@ManyToOne(fetch=FetchType.LAZY,targetEntity=LkuData.class)
	@JoinColumn(name="`report_lku_id`")
	private LkuData reportLookup;
	
	@ManyToOne(fetch=FetchType.LAZY,targetEntity=Item.class)
	@JoinColumn(name="`item_id`")
	private Item item;
	 
	@ManyToOne(fetch=FetchType.LAZY,targetEntity=DataCenterLocationDetails.class)
	@JoinColumn(name="`location_id`")
	private DataCenterLocationDetails dataCenterLocation;
	
	@ManyToOne(fetch=FetchType.LAZY,targetEntity=Users.class)
	@JoinColumn(name="`user_id`")
	private Users user;
	 
	@Column(name="`thresholds`")
	private String thresholds;
	 
	@Column(name="`update_date`")
	private Timestamp updateDate;

	public ReportThresholds() {
	}
	
	public ReportThresholds(Long id, LkuData reportLookup, DataCenterLocationDetails  dataCenterLocation, Users user, String thresholds, Timestamp updateDate) {
		this.id=id;
		this.reportLookup = reportLookup;
		this.dataCenterLocation = dataCenterLocation;
		this.user = user;
		this.thresholds = thresholds;
		this.updateDate = updateDate;
	}
   
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}
	
	public LkuData getReportLookup() {
		return this.reportLookup;
	}
	
	public void setReportLookup(LkuData reportLookup) {
		this.reportLookup = reportLookup;
	}
	
	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}
	
	public DataCenterLocationDetails getDataCenterLocation() {
		return dataCenterLocation;
	}

	public void setDataCenterLocation(DataCenterLocationDetails dataCenterLocation) {
		this.dataCenterLocation = dataCenterLocation;
	}
	
	public Users getUser() {
		return this.user;
	}
	
	public void setUser(Users user) {
		this.user = user;
	}
	
	public String getThresholds() {
		return this.thresholds;
	}
	
	public void setThresholds(String thresholds) {
		this.thresholds = thresholds;
	}
	
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}
	
	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}


}


